### ISSUE TITLE
Incluir resíduos eletroeletrônicos

### ISSUE THREAD

**Issue by AndreaInfUFSM** [Felipe-Marin/Projeto-de-Software-II#8]
- Adicionar no mapa os pontos de coleta deste tipo de resíduo
- Ícone deve, preferencialmente, ser um tonel azul, pois é a cor dos coletores usados na UFSM para este tipo de material.
- Incluir também esses resíduos na lista para busca e na lista explicativa dos tipos de resíduos.

**Comment by Felipe-Marin** [comment]
Adicionado a categoria de resíduos eletroeletrônicos no mapa e busca, falta informação da localização e resíduos para lista de busca.
