### ISSUE TITLE
Lâmpadas e outros tipos

### ISSUE THREAD

**Issue by AndreaInfUFSM** [Felipe-Marin/Projeto-de-Software-II#9]
Há outros tipos de resíduos (resíduos especiais) que não ficarão no mapa, mas o aplicativo deve ajudar o usuário a descobrir como descartá-los (usar categoria 'resíduos especiais').
Mais informações: http://coral.ufsm.br/coletaseletiva/index.php/tipos-de-coleta/residuos-especiais

**Comment by Felipe-Marin** [comment]
Inserida categoria de resíduos especiais
